import sys
from PySide2 import QtWidgets,QtCore,QtGui
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from . import camera_presets as cp

class Ui_Form(QtWidgets.QWidget):
	def __init__(self, parent=None):
		super(Ui_Form, self).__init__(parent)

		self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
		
		style_file = "D:\\MTL\\SRP2\\kphan\\Camera\\addons\\mtl\\qss\\styledark.qss"
		with open(style_file,"r") as f:
			_style = f.read()
			self.setStyleSheet(_style)

		if not self.objectName():
			self.setObjectName(u"Form")
		self.resize(351, 571)
		self.setAutoFillBackground(False)

		self.tabWidget = QTabWidget(self)
		self.tabWidget.setObjectName(u"tabWidget")
		self.tabWidget.setGeometry(QRect(0, 0, 341, 571))
		self.tabWidget.setAutoFillBackground(True)
		
		self.tab = QWidget()
		self.tab.setObjectName(u"tab")

		self.groupBox_5 = QGroupBox(self.tab)
		self.groupBox_5.setObjectName(u"groupBox_5")
		self.groupBox_5.setGeometry(QRect(10, 0, 311, 81))
		self.groupBox_5.setAlignment(Qt.AlignCenter)
		self.groupBox_5.setFlat(True)
		self.groupBox_5.setCheckable(False)
		self.add_cam_btn = QPushButton(self.groupBox_5)
		self.add_cam_btn.setObjectName(u"add_cam_btn")
		self.add_cam_btn.setGeometry(QRect(10, 20, 75, 23))
		self.camera_CB = QComboBox(self.groupBox_5)
		self.camera_CB.setObjectName(u"camera_CB")
		self.camera_CB.setGeometry(QRect(10, 50, 261, 22))

		self.groupBox = QGroupBox(self.tab)
		self.groupBox.setObjectName(u"groupBox")
		self.groupBox.setGeometry(QRect(10, 80, 151, 141))
		self.groupBox.setAlignment(Qt.AlignCenter)
		self.groupBox.setFlat(True)
		self.shot_btn_group = QButtonGroup(self.groupBox)
		self.mid_full_btn = QPushButton(self.groupBox)
		self.mid_full_btn.setObjectName(u"mid_full")
		self.mid_full_btn.setGeometry(QRect(10, 20, 61, 23))
		self.mid_full_btn.setCheckable(True)
		self.mid_full_btn.setChecked(False)
		self.full_btn = QPushButton(self.groupBox)
		self.full_btn.setObjectName(u"full")
		self.full_btn.setGeometry(QRect(80, 20, 61, 23))
		self.full_btn.setCheckable(True)
		self.full_btn.setChecked(False)
		self.close_up_btn = QPushButton(self.groupBox)
		self.close_up_btn.setObjectName(u"close up")
		self.close_up_btn.setGeometry(QRect(10, 50, 61, 23))
		self.close_up_btn.setCheckable(True)
		self.close_up_btn.setChecked(False)
		self.medium_btn = QPushButton(self.groupBox)
		self.medium_btn.setObjectName(u"medium")
		self.medium_btn.setGeometry(QRect(80, 50, 61, 23))
		self.medium_btn.setCheckable(True)
		self.medium_btn.setChecked(False)
		self.extreme_close_btn = QPushButton(self.groupBox)
		self.extreme_close_btn.setObjectName(u"extreme close up")
		self.extreme_close_btn.setGeometry(QRect(80, 80, 61, 23))
		self.extreme_close_btn.setCheckable(True)
		self.extreme_close_btn.setChecked(False)
		self.long_btn = QPushButton(self.groupBox)
		self.long_btn.setObjectName(u"long")
		self.long_btn.setGeometry(QRect(10, 80, 61, 23))
		self.long_btn.setCheckable(True)
		self.long_btn.setChecked(False)
		self.mid_close_btn = QPushButton(self.groupBox)
		self.mid_close_btn.setObjectName(u"medium close up")
		self.mid_close_btn.setGeometry(QRect(80, 110, 61, 23))
		self.mid_close_btn.setCheckable(True)
		self.mid_close_btn.setChecked(False)
		self.cowboy_btn = QPushButton(self.groupBox)
		self.cowboy_btn.setObjectName(u"cowboy")
		self.cowboy_btn.setGeometry(QRect(10, 110, 61, 23))
		self.cowboy_btn.setCheckable(True)
		self.cowboy_btn.setChecked(False)

		self.shot_btn_group.addButton(self.mid_full_btn)
		self.shot_btn_group.addButton(self.full_btn)
		self.shot_btn_group.addButton(self.close_up_btn)
		self.shot_btn_group.addButton(self.medium_btn)
		self.shot_btn_group.addButton(self.extreme_close_btn)
		self.shot_btn_group.addButton(self.long_btn)
		self.shot_btn_group.addButton(self.mid_close_btn)
		self.shot_btn_group.addButton(self.cowboy_btn)
		self.shot_btn_group.setExclusive(False)


		self.groupBox_2 = QGroupBox(self.tab)
		self.groupBox_2.setObjectName(u"groupBox_2")
		self.groupBox_2.setGeometry(QRect(170, 80, 151, 141))
		self.groupBox_2.setAlignment(Qt.AlignCenter)
		self.groupBox_2.setFlat(True)
		self.angle_btn_group = QButtonGroup(self.groupBox_2)
		self.shoudler_btn = QPushButton(self.groupBox_2)
		self.shoudler_btn.setObjectName(u"shoulder_level")
		self.shoudler_btn.setGeometry(QRect(10, 50, 61, 23))
		self.shoudler_btn.setCheckable(True)
		self.shoudler_btn.setChecked(False)
		self.low_btn = QPushButton(self.groupBox_2)
		self.low_btn.setObjectName(u"low")
		self.low_btn.setGeometry(QRect(80, 20, 61, 23))
		self.low_btn.setCheckable(True)
		self.low_btn.setChecked(False)
		self.high_btn = QPushButton(self.groupBox_2)
		self.high_btn.setObjectName(u"high")
		self.high_btn.setGeometry(QRect(10, 20, 61, 23))
		self.high_btn.setCheckable(True)
		self.high_btn.setChecked(False)
		self.eye_btn = QPushButton(self.groupBox_2)
		self.eye_btn.setObjectName(u"eye_level")
		self.eye_btn.setGeometry(QRect(80, 50, 61, 23))
		self.eye_btn.setCheckable(True)
		self.eye_btn.setChecked(False)

		self.angle_btn_group.addButton(self.shoudler_btn)
		self.angle_btn_group.addButton(self.low_btn)
		self.angle_btn_group.addButton(self.high_btn)
		self.angle_btn_group.addButton(self.eye_btn)
		self.angle_btn_group.setExclusive(False)

		self.groupBox_3 = QGroupBox(self.tab)
		self.groupBox_3.setObjectName(u"groupBox_3")
		self.groupBox_3.setGeometry(QRect(10, 220, 311, 50))
		self.groupBox_3.setAlignment(Qt.AlignCenter)
		self.groupBox_3.setFlat(True)
		self.dutch_btn_group = QButtonGroup(self.groupBox_3)
		self.tilt_left_btn = QPushButton(self.groupBox_3)
		self.tilt_left_btn.setObjectName(u"left")
		self.tilt_left_btn.setGeometry(QRect(10, 20, 75, 23))
		self.tilt_left_btn.setCheckable(True)
		self.tilt_left_btn.setChecked(False)
		self.no_tilt_btn = QPushButton(self.groupBox_3)
		self.no_tilt_btn.setObjectName(u"no")
		self.no_tilt_btn.setGeometry(QRect(120, 20, 75, 23))
		self.no_tilt_btn.setCheckable(True)
		self.no_tilt_btn.setChecked(False)
		self.tilt_right_btn = QPushButton(self.groupBox_3)
		self.tilt_right_btn.setObjectName(u"right")
		self.tilt_right_btn.setGeometry(QRect(230, 20, 71, 23))
		self.tilt_right_btn.setCheckable(True)
		self.tilt_right_btn.setChecked(False)
		self.tilt_right_btn.setFlat(False)

		self.dutch_btn_group.addButton(self.tilt_left_btn)
		self.dutch_btn_group.addButton(self.no_tilt_btn)
		self.dutch_btn_group.addButton(self.tilt_right_btn)
		self.dutch_btn_group.setExclusive(False)

		self.groupBox_4 = QGroupBox(self.tab)
		self.groupBox_4.setObjectName(u"groupBox_4")
		self.groupBox_4.setGeometry(QRect(10, 270, 151, 261))
		self.groupBox_4.setAlignment(Qt.AlignCenter)
		self.groupBox_4.setFlat(True)
		self.track_btn_group = QButtonGroup(self.groupBox_4)
		self.pan_left_btn = QPushButton(self.groupBox_4)
		self.pan_left_btn.setObjectName(u"Left")
		self.pan_left_btn.setGeometry(QRect(10, 50, 61, 23))
		self.pan_left_btn.setCheckable(True)
		self.pan_left_btn.setChecked(False)
		self.tilt_up_btn = QPushButton(self.groupBox_4)
		self.tilt_up_btn.setObjectName(u"Up")
		self.tilt_up_btn.setGeometry(QRect(10, 80, 61, 23))
		self.tilt_up_btn.setCheckable(True)
		self.tilt_up_btn.setChecked(False)
		self.truck_back_btn = QPushButton(self.groupBox_4)
		self.truck_back_btn.setObjectName(u"Backwards")
		self.truck_back_btn.setGeometry(QRect(10, 110, 61, 23))
		self.truck_back_btn.setCheckable(True)
		self.truck_back_btn.setChecked(False)
		self.dolly_left_btn = QPushButton(self.groupBox_4)
		self.dolly_left_btn.setObjectName(u"Left")
		self.dolly_left_btn.setGeometry(QRect(10, 140, 61, 23))
		self.dolly_left_btn.setCheckable(True)
		self.dolly_left_btn.setChecked(False)
		self.tilt_down_btn = QPushButton(self.groupBox_4)
		self.tilt_down_btn.setObjectName(u"Down")
		self.tilt_down_btn.setGeometry(QRect(80, 80, 61, 23))
		self.tilt_down_btn.setCheckable(True)
		self.tilt_down_btn.setChecked(False)
		self.pan_right_btn = QPushButton(self.groupBox_4)
		self.pan_right_btn.setObjectName(u"Right")
		self.pan_right_btn.setGeometry(QRect(80, 50, 61, 23))
		self.pan_right_btn.setCheckable(True)
		self.pan_right_btn.setChecked(False)
		self.dolly_right_btn = QPushButton(self.groupBox_4)
		self.dolly_right_btn.setObjectName(u"Right")
		self.dolly_right_btn.setGeometry(QRect(80, 140, 61, 23))
		self.dolly_right_btn.setCheckable(True)
		self.dolly_right_btn.setChecked(False)
		self.truck_forward_btn = QPushButton(self.groupBox_4)
		self.truck_forward_btn.setObjectName(u"Forwards")
		self.truck_forward_btn.setGeometry(QRect(80, 110, 61, 23))
		self.truck_forward_btn.setCheckable(True)
		self.truck_forward_btn.setChecked(False)
		self.zoom_in_btn = QPushButton(self.groupBox_4)
		self.zoom_in_btn.setObjectName(u"In")
		self.zoom_in_btn.setGeometry(QRect(10, 170, 61, 23))
		self.zoom_in_btn.setCheckable(True)
		self.zoom_in_btn.setChecked(False)
		self.zoom_out_btn = QPushButton(self.groupBox_4)
		self.zoom_out_btn.setObjectName(u"Out")
		self.zoom_out_btn.setGeometry(QRect(80, 170, 61, 23))
		self.zoom_out_btn.setCheckable(True)
		self.zoom_out_btn.setChecked(False)
		self.duration_sp = QSpinBox(self.groupBox_4)
		self.duration_sp.setObjectName(u"duration")
		self.duration_sp.setGeometry(QRect(80, 20, 61, 22))
		self.duration_sp.setReadOnly(False)
		self.duration_sp.setValue(50)
		self.duration_sp.setMaximum(1000)
		self.label_duration = QLabel(self.groupBox_4)
		self.label_duration.setObjectName(u"label_duration")
		self.label_duration.setGeometry(QRect(10, 20, 61, 21))
		self.label_duration.setAlignment(Qt.AlignCenter)
		self.reset_btn = QPushButton(self.groupBox_4)
		self.reset_btn.setObjectName(u"reset_btn")
		self.reset_btn.setEnabled(True)
		self.reset_btn.setGeometry(QRect(10, 200, 131, 41))
		self.reset_btn.setCheckable(False)
		self.reset_btn.setChecked(False)
		self.reset_btn.setStyleSheet(u"background-color: rgb(35, 35, 35);\n" "color: rgb(177, 177, 177);")

		self.track_btn_group.addButton(self.pan_left_btn)
		self.track_btn_group.addButton(self.tilt_up_btn)
		self.track_btn_group.addButton(self.truck_back_btn)
		self.track_btn_group.addButton(self.dolly_left_btn)
		self.track_btn_group.addButton(self.tilt_down_btn)
		self.track_btn_group.addButton(self.pan_right_btn)
		self.track_btn_group.addButton(self.dolly_right_btn)
		self.track_btn_group.addButton(self.truck_forward_btn)
		self.track_btn_group.addButton(self.zoom_in_btn)
		self.track_btn_group.addButton(self.zoom_out_btn)
		self.track_btn_group.setExclusive(False)


		self.groupBox_6 = QGroupBox(self.tab)
		self.groupBox_6.setObjectName(u"groupBox_6")
		self.groupBox_6.setGeometry(QRect(170, 270, 151, 111))
		self.groupBox_6.setAlignment(Qt.AlignCenter)
		self.groupBox_6.setFlat(True)
		self.framing_btn_group = QButtonGroup(self.groupBox_6)
		self.middle_btn = QPushButton(self.groupBox_6)
		self.middle_btn.setObjectName(u"middle middle")
		self.middle_btn.setGeometry(QRect(10, 50, 131, 23))
		self.middle_btn.setCheckable(True)
		self.middle_btn.setChecked(False)
		self.top_left_btn = QPushButton(self.groupBox_6)
		self.top_left_btn.setObjectName(u"top left")
		self.top_left_btn.setGeometry(QRect(10, 20, 61, 23))
		self.top_left_btn.setCheckable(True)
		self.top_left_btn.setChecked(False)
		self.top_right_btn = QPushButton(self.groupBox_6)
		self.top_right_btn.setObjectName(u"top right")
		self.top_right_btn.setGeometry(QRect(80, 20, 61, 23))
		self.top_right_btn.setCheckable(True)
		self.top_right_btn.setChecked(False)
		self.bottom_left_btn = QPushButton(self.groupBox_6)
		self.bottom_left_btn.setObjectName(u"bottom left")
		self.bottom_left_btn.setGeometry(QRect(80, 80, 61, 23))
		self.bottom_left_btn.setCheckable(True)
		self.bottom_left_btn.setChecked(False)
		self.bottom_right_btn = QPushButton(self.groupBox_6)
		self.bottom_right_btn.setObjectName(u"bottom right")
		self.bottom_right_btn.setGeometry(QRect(10, 80, 61, 23))
		self.bottom_right_btn.setCheckable(True)
		self.bottom_right_btn.setChecked(False)

		self.framing_btn_group.addButton(self.middle_btn)
		self.framing_btn_group.addButton(self.top_left_btn)
		self.framing_btn_group.addButton(self.top_right_btn)
		self.framing_btn_group.addButton(self.bottom_left_btn)
		self.framing_btn_group.addButton(self.bottom_right_btn)
		self.framing_btn_group.setExclusive(False)



		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QWidget()
		self.tab_2.setObjectName(u"tab_2")
		self.listWidget = QListWidget(self.tab_2)
		self.listWidget.setObjectName(u"listWidget")
		self.listWidget.setGeometry(QRect(10, 10, 311, 192))
		self.add_json_btn = QPushButton(self.tab_2)
		self.add_json_btn.setObjectName(u"pushButton_36")
		self.add_json_btn.setGeometry(QRect(10, 210, 75, 23))
		self.batch_btn = QPushButton(self.tab_2)
		self.batch_btn.setObjectName(u"pushButton_37")
		self.batch_btn.setGeometry(QRect(90, 210, 231, 23))
		self.tabWidget.addTab(self.tab_2, "")

		self.retranslateUi()

		self.tabWidget.setCurrentIndex(0)

		QMetaObject.connectSlotsByName(self)

	def retranslateUi(self):
		self.setWindowTitle(QCoreApplication.translate("Form", u"Camera Plugin", None))
		self.groupBox.setTitle(QCoreApplication.translate("Form", u"Shot Type", None))
		self.mid_full_btn.setText(QCoreApplication.translate("Form", u"Mid Full", None))
		self.full_btn.setText(QCoreApplication.translate("Form", u"Full", None))
		self.close_up_btn.setText(QCoreApplication.translate("Form", u"Close Up", None))
		self.medium_btn.setText(QCoreApplication.translate("Form", u"Mid", None))
		self.extreme_close_btn.setText(QCoreApplication.translate("Form", u"Ext Close", None))
		self.long_btn.setText(QCoreApplication.translate("Form", u"Long", None))
		self.mid_close_btn.setText(QCoreApplication.translate("Form", u"Mid Close", None))
		self.cowboy_btn.setText(QCoreApplication.translate("Form", u"Cowboy", None))
		self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"Angle Type", None))
		self.shoudler_btn.setText(QCoreApplication.translate("Form", u"Shoulder", None))
		self.low_btn.setText(QCoreApplication.translate("Form", u"Low", None))
		self.high_btn.setText(QCoreApplication.translate("Form", u"High", None))
		self.eye_btn.setText(QCoreApplication.translate("Form", u"Eye", None))
		self.groupBox_5.setTitle(QCoreApplication.translate("Form", u"Camera", None))
		self.add_cam_btn.setText(QCoreApplication.translate("Form", u"Add Camera", None))
		self.camera_CB.setPlaceholderText("")
		self.groupBox_3.setTitle(QCoreApplication.translate("Form", u"Dutch Tilt", None))
		self.tilt_left_btn.setText(QCoreApplication.translate("Form", u"Left", None))
		self.no_tilt_btn.setText(QCoreApplication.translate("Form", u"None", None))
		self.tilt_right_btn.setText(QCoreApplication.translate("Form", u"Right", None))

		self.groupBox_4.setTitle(QCoreApplication.translate("Form", u"Tracking", None))
		self.pan_left_btn.setText(QCoreApplication.translate("Form", u"Pan Left", None))
		self.tilt_up_btn.setText(QCoreApplication.translate("Form", u"Tilt Up", None))
		self.truck_back_btn.setText(QCoreApplication.translate("Form", u"Truck Back", None))
		self.dolly_left_btn.setText(QCoreApplication.translate("Form", u"Dolly Left", None))
		self.tilt_down_btn.setText(QCoreApplication.translate("Form", u"Tilt Down", None))
		self.pan_right_btn.setText(QCoreApplication.translate("Form", u"Pan Right", None))
		self.dolly_right_btn.setText(QCoreApplication.translate("Form", u"Dolly Right", None))
		self.truck_forward_btn.setText(QCoreApplication.translate("Form", u"Truck Forward", None))
		self.zoom_in_btn.setText(QCoreApplication.translate("Form", u"Zoom In", None))
		self.zoom_out_btn.setText(QCoreApplication.translate("Form", u"Zoom Out", None))

		self.groupBox_6.setTitle(QCoreApplication.translate("Form", u"Framing (Rule of Third)", None))
		self.middle_btn.setText(QCoreApplication.translate("Form", u"Middle", None))
		self.top_left_btn.setText(QCoreApplication.translate("Form", u"Top Left", None))
		self.top_right_btn.setText(QCoreApplication.translate("Form", u"Top Right", None))
		self.bottom_left_btn.setText(QCoreApplication.translate("Form", u"Bottom Left", None))
		self.bottom_right_btn.setText(QCoreApplication.translate("Form", u"Bottom Right", None))
		self.label_duration.setText(QCoreApplication.translate("Form", u"Duration", None))
		self.reset_btn.setText(QCoreApplication.translate("Form", u"Reset", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"Camera", None))
		self.add_json_btn.setText(QCoreApplication.translate("Form", u"Add Json", None))
		self.batch_btn.setText(QCoreApplication.translate("Form", u"Batch Export", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"Batch Export", None))
		
        